version: "3.8"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      - "${DB_PORT}:3306"
    networks:
      - ideasync
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql

  system-init:
    build:
      context: .
      dockerfile: ./system-init/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - BASE_URL=${BASE_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    networks:
      - ideasync

  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
      - spring.application.name=idea-sync-backend
      - spring.datasource.url=jdbc:mysql://db:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      - spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      - spring.jpa.show-sql=true
      - spring.jpa.properties.hibernate.jdbc.time_zone=UTC
      - spring.mail.host=smtp.gmail.com
      - spring.mail.port=587
      - spring.mail.username=${COMPANY_EMAIL}
      - spring.mail.password=${COMPANY_EMAIL_PASSWORD}
      - spring.mail.properties.mail.smtp.auth=true
      - spring.mail.properties.mail.smtp.starttls.enable=true
      - spring.ai.vectorstore.pinecone.apiKey=${PINECONE_API_KEY}
      - spring.ai.vectorstore.pinecone.environment=aped-4627-b74a
      - spring.ai.vectorstore.pinecone.projectId=rq4bkeq
      - spring.ai.vectorstore.pinecone.index-name=tag-embedding
      - logging.level.org.springframework.security=TRACE
      - PUBLIC_KEY=${PUBLIC_KEY}
      - PRIVATE_KEY=${PRIVATE_KEY}
    networks:
      - ideasync
    depends_on:
      - db

  ui:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - ideasync
    environment:
      - NUXT_PUBLIC_BASE_URL=${NUXT_PUBLIC_BASE_URL}
      - NUXT_AWS_ACCESS_KEY=${NUXT_AWS_ACCESS_KEY}
      - NUXT_AWS_SECRET_ACCESS_KEY=${NUXT_AWS_SECRET_ACCESS_KEY}
      - NUXT_AWS_BUCKET_NAME=${NUXT_AWS_BUCKET_NAME}
      - NUXT_AWS_BUCKET_REGION=${NUXT_AWS_BUCKET_REGION}
networks:
  ideasync:
volumes:
  mysql-data:
